target:
	gcc P1.c -o P1.out -lpthread
	gcc P2.c -o P2.out -lpthread
	gcc P3.c -o P3.out -lpthread
	gcc scheduler.c -o scheduler.out -lpthread
	gcc dummy1.c -o dummy1.out -lpthread
	gcc dummy2.c -o dummy2.out -lpthread